server:
  port: 8080

#database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ms_tour?useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&useAffectedRows=true
    username: root
    password: password

#mybatis
mybatis:
  #classpath：只会到你的class路径中查找找文件;
  #classpath*：不仅包含class路径，还包括jar文件中(class路径)进行查找
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.shh.persistence.entity
  config-location: classpath:mybatis-config.xml


